@startuml
class Router {
'   - admin: String
'   - cart: String
'   - checkout: String
'   - homepage: String
'   - product: String
'   - shop: String
'   - user: String
'   + setRoute(path: String, method: String): void
-user
}

class UserController {
  - signUp
  - signIn
  - loginSuccess
  - register
  - login
  - logout
    -info
    -change_Info
    -showPurchase
}

class Middleware {
  + authenticate
  + authorize
  + findUser
  + sort
}
class Model {
  - order
  - user
  - product
}


Router --> Middleware
UserController --> Model
Middleware --> UserController
@enduml